In [275]:
import pandas as pd
import matplotlib.pyplot as plt

In [276]:
df = pd.read_csv("social_media_impact.csv")
print(df)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat
1     STU_2024001   19  Female  Undergraduate        Instagram
2     STU_2024002   17  Female    High School           TikTok
3     STU_2024003   16  Female    High School          YouTube
4     STU_2024004   17    Male    High School         LinkedIn
...           ...  ...     ...            ...              ...
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
1                   4.6                  1.3  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
4                   3.3                  2.6  Smartphone
...                 ...                  ...         ...
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
1                      7.9                    3              True
2                      5.2                    1              True
3                      7.6                    4              True
4                      7.6                    4              True
...                    ...                  ...               ...
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
1                      Sometimes                    17.0                   90
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
4                          Never                    16.0                   84
...                          ...                     ...                  ...
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
1                         3.21     Beneficial
2                         3.00        Neutral
3                         3.42     Beneficial
4                         3.41     Beneficial
...                        ...            ...
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

[4500 rows x 16 columns]

In [277]:
print(df.shape) # This will print the number of rows and columns in the DataFrame

(4500, 16)

In [278]:
print(df.columns) # This will print the column names of the DataFrame

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='object')

In [279]:
print(df.info()) # This will print a concise summary of the DataFrame, including the data types and non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(3), object(7)
memory usage: 531.9+ KB
None

In [280]:
average_stress = df["Perceived_Stress_Score"].mean()

print(average_stress) # This will print the average perceived stress score

13.512123933542883

In [281]:
average_gpa = df["Academic_Performance_GPA"].mean()

print(average_gpa) # This will print the average perceived GPA score

3.4292819932049827

In [282]:
df["Perceived_Stress_Score"] = df["Perceived_Stress_Score"].fillna(average_stress)

In [283]:
print(df.head(10)) # This will print the first 10 rows of the DataFrame

    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok
3  STU_2024003   16  Female    High School          YouTube
4  STU_2024004   17    Male    High School         LinkedIn
5  STU_2024005   16    Male    High School           TikTok
6  STU_2024006   20    Male  Undergraduate           TikTok
7  STU_2024007   19  Female  Undergraduate           TikTok
8  STU_2024008   18  Female  Undergraduate          YouTube
9  STU_2024009   18  Female  Undergraduate           Reddit

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2
3                6.0                  2.3      Tablet                   7.6
4                3.3                  2.6  Smartphone                   7.6
5                6.2                  1.6  Smartphone                   5.9
6                5.6                  1.8  Smartphone                   8.3
7                1.2                  2.4  Smartphone                   8.1
8                3.3                  1.8  Smartphone                   6.4
9                4.7                  1.7  Smartphone                   7.9

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently
3                    4              True                   Sometimes
4                    4              True                       Never
5                    1             False                      Rarely
6                    3             False                   Sometimes
7                    5             False                      Always
8                    2             False                  Frequently
9                    2             False                  Frequently

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00
3                    15.0                   82                      3.42
4                    16.0                   84                      3.41
5                    10.0                   66                      3.21
6                    10.0                   88                      3.72
7                     6.0                   95                      3.37
8                    23.0                   88                      3.59
9                     6.0                   96                      3.66

  Overall_Impact
0        Neutral
1     Beneficial
2        Neutral
3     Beneficial
4     Beneficial
5     Beneficial
6     Beneficial
7     Beneficial
8     Beneficial
9     Beneficial

In [284]:
print(df.tail(10)) # This will print the last 10 rows of the DataFrame

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
4490  STU_2028490   19    Male  Undergraduate           TikTok
4491  STU_2028491   18  Female    High School          YouTube
4492  STU_2028492   22    Male   Postgraduate         Snapchat
4493  STU_2028493   18  Female  Undergraduate          YouTube
4494  STU_2028494   16    Male    High School          YouTube
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
4490                4.0                  1.8  Smartphone
4491                9.7                  1.9  Smartphone
4492                3.6                  2.5  Smartphone
4493                4.5                  2.4  Smartphone
4494                5.2                  1.6  Smartphone
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
4490                   6.3                    3             False
4491                   4.2                    1              True
4492                   7.0                    4              True
4493                   8.2                    4              True
4494                   5.7                    3              True
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
4490                   Sometimes                    13.0                   74
4491                   Sometimes                    21.0                   63
4492                  Frequently                    11.0                   92
4493                   Sometimes                     0.0                   85
4494                   Sometimes                    24.0                   77
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
4490                      4.00     Beneficial
4491                      2.73        Neutral
4492                      3.42     Beneficial
4493                      3.75     Beneficial
4494                      3.31        Neutral
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

In [285]:
df["Academic_Performance_GPA"] = df["Academic_Performance_GPA"].fillna(average_gpa)

In [286]:
print(df.isna().sum()) # This will print the number of missing values in each column of the DataFrame

Student_ID                     0
Age                            0
Gender                         0
Academic_Level                 0
Primary_Platform               0
Daily_Usage_Hours              0
Weekend_Extra_Hours            0
Device_Type                    0
Sleep_Duration_Hours           0
Sleep_Quality_Score            0
Late_Night_Usage               0
Social_Comparison_Frequency    0
Perceived_Stress_Score         0
Mental_Health_Index            0
Academic_Performance_GPA       0
Overall_Impact                 0
dtype: int64

In [287]:
age_column = df["Age"]
print(age_column) # This will print the "Age" column of the DataFrame

0       19
1       19
2       17
3       16
4       17
        ..
4495    16
4496    19
4497    19
4498    16
4499    24
Name: Age, Length: 4500, dtype: int64

In [288]:
Daily_Usage_Hours = df["Daily_Usage_Hours"]
print(Daily_Usage_Hours) # This will print the "Daily_Usage_Hours
df.describe()

0        7.5
1        4.6
2       10.9
3        6.0
4        3.3
        ...
4495     5.8
4496     3.8
4497     7.7
4498     4.6
4499     1.8
Name: Daily_Usage_Hours, Length: 4500, dtype: float64

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.036608,12.876044,0.388935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.450000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [289]:
Weekend_Extra_Hours = df["Weekend_Extra_Hours"]
print(Weekend_Extra_Hours) # This will print the "Weekend_Extra_Hours
df.describe()

0       1.5
1       1.3
2       1.7
3       2.3
4       2.6
       ...
4495    1.2
4496    3.0
4497    1.1
4498    3.3
4499    2.1
Name: Weekend_Extra_Hours, Length: 4500, dtype: float64

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.036608,12.876044,0.388935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.450000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [290]:
Sleep_Duration_Hours = df["Sleep_Duration_Hours"]
print(Sleep_Duration_Hours) # This will print the "Sleep_Duration_Hours
df.describe()

0       5.9
1       7.9
2       5.2
3       7.6
4       7.6
       ...
4495    7.8
4496    6.6
4497    6.0
4498    7.1
4499    6.8
Name: Sleep_Duration_Hours, Length: 4500, dtype: float64

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.036608,12.876044,0.388935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.450000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [291]:
Sleep_Quality_Score = df["Sleep_Quality_Score"]
print(Sleep_Quality_Score) # This will print the "Sleep_Quality_Score
df.describe()

0       2
1       3
2       1
3       4
4       4
       ..
4495    3
4496    3
4497    2
4498    3
4499    3
Name: Sleep_Quality_Score, Length: 4500, dtype: int64

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.036608,12.876044,0.388935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.450000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [292]:
Perceived_Stress_Score = df["Perceived_Stress_Score"]
print(Perceived_Stress_Score) # This will print the "Perceived_Stress
df.describe()

0       20.0
1       17.0
2       18.0
3       15.0
4       16.0
        ...
4495    11.0
4496     9.0
4497    13.0
4498    22.0
4499    10.0
Name: Perceived_Stress_Score, Length: 4500, dtype: float64

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.036608,12.876044,0.388935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.450000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [293]:
Mental_Health_Index = df["Mental_Health_Index"]
print(Mental_Health_Index)
df.describe()

0       73
1       90
2       70
3       82
4       84
        ..
4495    79
4496    83
4497    73
4498    87
4499    98
Name: Mental_Health_Index, Length: 4500, dtype: int64

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.036608,12.876044,0.388935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.450000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [294]:
Academic_Performance_GPA = df["Academic_Performance_GPA"]
print(Academic_Performance_GPA) # This will print the "Academic_Performance_GPA"
df.describe() # This will print the summary statistics of the DataFrame

0       2.73
1       3.21
2       3.00
3       3.42
4       3.41
        ...
4495    2.85
4496    3.37
4497    3.16
4498    3.50
4499    3.73
Name: Academic_Performance_GPA, Length: 4500, dtype: float64

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.036608,12.876044,0.388935
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.450000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [295]:
primaty_platform_column = df["Primary_Platform"]
print(primaty_platform_column)

0        Snapchat
1       Instagram
2          TikTok
3         YouTube
4        LinkedIn
          ...
4495      YouTube
4496     LinkedIn
4497    Instagram
4498     LinkedIn
4499    Instagram
Name: Primary_Platform, Length: 4500, dtype: object

In [296]:
Student_ID_column = df["Student_ID"]
print(Student_ID_column)

0       STU_2024000
1       STU_2024001
2       STU_2024002
3       STU_2024003
4       STU_2024004
           ...
4495    STU_2028495
4496    STU_2028496
4497    STU_2028497
4498    STU_2028498
4499    STU_2028499
Name: Student_ID, Length: 4500, dtype: object

In [297]:
Gender_column = df["Gender"]
print(Gender_column)

0       Female
1       Female
2       Female
3       Female
4         Male
         ...
4495      Male
4496    Female
4497      Male
4498      Male
4499      Male
Name: Gender, Length: 4500, dtype: object

In [298]:
Academic_Level_column = df["Academic_Level"]
print(Academic_Level_column)

0       Undergraduate
1       Undergraduate
2         High School
3         High School
4         High School
            ...
4495      High School
4496    Undergraduate
4497    Undergraduate
4498      High School
4499    Undergraduate
Name: Academic_Level, Length: 4500, dtype: object

In [299]:
Device_Type_column = df["Device_Type"]
print(Device_Type_column)

0       Smartphone
1       Smartphone
2       Smartphone
3           Tablet
4       Smartphone
           ...
4495    Smartphone
4496    Smartphone
4497    Smartphone
4498     Laptop/PC
4499    Smartphone
Name: Device_Type, Length: 4500, dtype: object

In [300]:
Late_Night_Usage_column = df["Late_Night_Usage"]
print(Late_Night_Usage_column)

0        True
1        True
2        True
3        True
4        True
        ...
4495     True
4496    False
4497     True
4498    False
4499     True
Name: Late_Night_Usage, Length: 4500, dtype: bool

In [301]:
Social_Comparison_Frequency_column = df["Social_Comparison_Frequency"]
print(Social_Comparison_Frequency_column)

0           Always
1        Sometimes
2       Frequently
3        Sometimes
4            Never
           ...
4495     Sometimes
4496    Frequently
4497    Frequently
4498     Sometimes
4499    Frequently
Name: Social_Comparison_Frequency, Length: 4500, dtype: object

In [302]:
Overall_Impact_column = df["Overall_Impact"]
print(Overall_Impact_column)

0          Neutral
1       Beneficial
2          Neutral
3       Beneficial
4       Beneficial
           ...
4495    Beneficial
4496    Beneficial
4497    Beneficial
4498    Beneficial
4499    Beneficial
Name: Overall_Impact, Length: 4500, dtype: object

In [303]:
print(primaty_platform_column.value_counts())

Primary_Platform
Instagram      1453
TikTok         1226
YouTube         818
Snapchat        472
Reddit          229
X (Twitter)     206
LinkedIn         96
Name: count, dtype: int64

In [304]:
print(Student_ID_column.value_counts())

Student_ID
STU_2024000    1
STU_2026998    1
STU_2027004    1
STU_2027003    1
STU_2027002    1
              ..
STU_2025505    1
STU_2025506    1
STU_2025507    1
STU_2025508    1
STU_2028499    1
Name: count, Length: 4500, dtype: int64

In [305]:
print(Gender_column.value_counts())

Gender
Female               2234
Male                 2051
Non-Binary            122
Prefer not to say      93
Name: count, dtype: int64

In [306]:
print(Academic_Level_column.value_counts())

Academic_Level
Undergraduate    2777
High School      1477
Postgraduate      246
Name: count, dtype: int64

In [307]:
print(Device_Type_column.value_counts())

Device_Type
Smartphone    3775
Laptop/PC      596
Tablet         129
Name: count, dtype: int64

In [308]:
print(Late_Night_Usage_column.value_counts())

Late_Night_Usage
True     2644
False    1856
Name: count, dtype: int64

In [309]:
print(Social_Comparison_Frequency_column.value_counts())

Social_Comparison_Frequency
Sometimes     1594
Frequently    1248
Rarely         766
Always         632
Never          260
Name: count, dtype: int64

In [310]:
print(Overall_Impact_column.value_counts())

Overall_Impact
Beneficial    3681
Neutral        654
Negative       165
Name: count, dtype: int64

In [311]:
daily_usage_hours_column = df["Daily_Usage_Hours"]
print(daily_usage_hours_column) # This will print the "Daily_Usage_Hours" column of the DataFrame

0        7.5
1        4.6
2       10.9
3        6.0
4        3.3
        ...
4495     5.8
4496     3.8
4497     7.7
4498     4.6
4499     1.8
Name: Daily_Usage_Hours, Length: 4500, dtype: float64

In [312]:
more_than_8h_online = df[daily_usage_hours_column > 8]
print(more_than_8h_online) # This will print the rows of the DataFrame where the daily usage hours are greater than 8
print(more_than_8h_online.shape[0])

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
2     STU_2024002   17             Female    High School           TikTok
12    STU_2024012   19             Female  Undergraduate           TikTok
23    STU_2024023   17             Female    High School        Instagram
31    STU_2024031   20               Male  Undergraduate      X (Twitter)
43    STU_2024043   20               Male  Undergraduate        Instagram
...           ...  ...                ...            ...              ...
4453  STU_2028453   18             Female  Undergraduate         Snapchat
4475  STU_2028475   18             Female    High School           TikTok
4476  STU_2028476   17             Female    High School           TikTok
4487  STU_2028487   17  Prefer not to say    High School        Instagram
4491  STU_2028491   18             Female    High School          YouTube

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2                  10.9                  1.7  Smartphone
12                  9.5                  0.9  Smartphone
23                 11.2                  1.7  Smartphone
31                  8.3                  1.8  Smartphone
43                  8.3                  2.2  Smartphone
...                 ...                  ...         ...
4453                9.1                  2.4  Smartphone
4475                8.6                  1.5   Laptop/PC
4476               11.1                  0.7  Smartphone
4487                8.8                  2.5  Smartphone
4491                9.7                  1.9  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2                      5.2                    1              True
12                     5.3                    1              True
23                     5.2                    2              True
31                     5.6                    1              True
43                     6.3                    1              True
...                    ...                  ...               ...
4453                   5.4                    3             False
4475                   6.0                    1              True
4476                   4.6                    1              True
4487                   6.2                    1              True
4491                   4.2                    1              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2                     Frequently                    18.0                   70
12                        Always                    27.0                   68
23                     Sometimes                    22.0                   54
31                        Rarely                    22.0                   64
43                     Sometimes                    13.0                   76
...                          ...                     ...                  ...
4453                       Never                    19.0                   67
4475                   Sometimes                    18.0                   63
4476                      Rarely                    32.0                   53
4487                  Frequently                    21.0                   68
4491                   Sometimes                    21.0                   63

      Academic_Performance_GPA Overall_Impact
2                         3.00        Neutral
12                        3.14        Neutral
23                        2.69        Neutral
31                        3.35        Neutral
43                        3.21     Beneficial
...                        ...            ...
4453                      3.25        Neutral
4475                      3.24        Neutral
4476                      2.56       Negative
4487                      3.50     Beneficial
4491                      2.73        Neutral

[632 rows x 16 columns]
632

In [313]:
primary_platform_column = df["Primary_Platform"]
print(primary_platform_column)

0        Snapchat
1       Instagram
2          TikTok
3         YouTube
4        LinkedIn
          ...
4495      YouTube
4496     LinkedIn
4497    Instagram
4498     LinkedIn
4499    Instagram
Name: Primary_Platform, Length: 4500, dtype: object

In [314]:
primary_platform_column == "TikTok"

0       False
1       False
2        True
3       False
4       False
        ...
4495    False
4496    False
4497    False
4498    False
4499    False
Name: Primary_Platform, Length: 4500, dtype: bool

In [315]:
tiktok_users = df[primary_platform_column == "TikTok"]
print(tiktok_users) # This will print the rows of the DataFrame where the primary platform

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
2     STU_2024002   17             Female    High School           TikTok
5     STU_2024005   16               Male    High School           TikTok
6     STU_2024006   20               Male  Undergraduate           TikTok
7     STU_2024007   19             Female  Undergraduate           TikTok
10    STU_2024010   15             Female    High School           TikTok
...           ...  ...                ...            ...              ...
4483  STU_2028483   17             Female    High School           TikTok
4484  STU_2028484   21               Male  Undergraduate           TikTok
4486  STU_2028486   20             Female  Undergraduate           TikTok
4489  STU_2028489   21  Prefer not to say    High School           TikTok
4490  STU_2028490   19               Male  Undergraduate           TikTok

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2                  10.9                  1.7  Smartphone
5                   6.2                  1.6  Smartphone
6                   5.6                  1.8  Smartphone
7                   1.2                  2.4  Smartphone
10                  4.4                  1.9  Smartphone
...                 ...                  ...         ...
4483                5.3                  2.2  Smartphone
4484                7.6                  1.0  Smartphone
4486                7.0                  1.8  Smartphone
4489                2.8                  3.2  Smartphone
4490                4.0                  1.8  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2                      5.2                    1              True
5                      5.9                    1             False
6                      8.3                    3             False
7                      8.1                    5             False
10                     5.8                    2             False
...                    ...                  ...               ...
4483                   6.5                    3              True
4484                   6.5                    1              True
4486                   5.4                    2              True
4489                   7.2                    4              True
4490                   6.3                    3             False

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2                     Frequently                    18.0                   70
5                         Rarely                    10.0                   66
6                      Sometimes                    10.0                   88
7                         Always                     6.0                   95
10                    Frequently                    11.0                   83
...                          ...                     ...                  ...
4483                  Frequently                    13.0                   82
4484                   Sometimes                    17.0                   70
4486                  Frequently                    12.0                   75
4489                      Rarely                     6.0                   98
4490                   Sometimes                    13.0                   74

      Academic_Performance_GPA Overall_Impact
2                         3.00        Neutral
5                         3.21     Beneficial
6                         3.72     Beneficial
7                         3.37     Beneficial
10                        3.22     Beneficial
...                        ...            ...
4483                      3.02     Beneficial
4484                      3.49     Beneficial
4486                      3.23     Beneficial
4489                      3.86     Beneficial
4490                      4.00     Beneficial

[1226 rows x 16 columns]

In [316]:
print(tiktok_users.shape[0])

1226

In [317]:
two_conditions = df[(df["Daily_Usage_Hours"] > 8) & (df["Sleep_Duration_Hours"] < 6)]
print(two_conditions)
display(two_conditions) # This will display the rows of the DataFrame where the daily usage hours are greater than 8 and the sleep duration hours are less than 6

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
2     STU_2024002   17  Female    High School           TikTok
12    STU_2024012   19  Female  Undergraduate           TikTok
23    STU_2024023   17  Female    High School        Instagram
31    STU_2024031   20    Male  Undergraduate      X (Twitter)
80    STU_2024080   18  Female  Undergraduate           TikTok
...           ...  ...     ...            ...              ...
4443  STU_2028443   19    Male  Undergraduate        Instagram
4450  STU_2028450   21    Male  Undergraduate          YouTube
4453  STU_2028453   18  Female  Undergraduate         Snapchat
4476  STU_2028476   17  Female    High School           TikTok
4491  STU_2028491   18  Female    High School          YouTube

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2                  10.9                  1.7  Smartphone
12                  9.5                  0.9  Smartphone
23                 11.2                  1.7  Smartphone
31                  8.3                  1.8  Smartphone
80                  8.5                  1.8  Smartphone
...                 ...                  ...         ...
4443                9.5                  1.9  Smartphone
4450                9.9                  1.7  Smartphone
4453                9.1                  2.4  Smartphone
4476               11.1                  0.7  Smartphone
4491                9.7                  1.9  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2                      5.2                    1              True
12                     5.3                    1              True
23                     5.2                    2              True
31                     5.6                    1              True
80                     5.5                    1              True
...                    ...                  ...               ...
4443                   5.1                    1              True
4450                   5.0                    1              True
4453                   5.4                    3             False
4476                   4.6                    1              True
4491                   4.2                    1              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2                     Frequently                    18.0                   70
12                        Always                    27.0                   68
23                     Sometimes                    22.0                   54
31                        Rarely                    22.0                   64
80                     Sometimes                    24.0                   67
...                          ...                     ...                  ...
4443                       Never                    16.0                   70
4450                   Sometimes                    30.0                   55
4453                       Never                    19.0                   67
4476                      Rarely                    32.0                   53
4491                   Sometimes                    21.0                   63

      Academic_Performance_GPA Overall_Impact
2                         3.00        Neutral
12                        3.14        Neutral
23                        2.69        Neutral
31                        3.35        Neutral
80                        2.79        Neutral
...                        ...            ...
4443                      2.38        Neutral
4450                      3.30        Neutral
4453                      3.25        Neutral
4476                      2.56       Negative
4491                      2.73        Neutral

[518 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
12,STU_2024012,19,Female,Undergraduate,TikTok,9.5,0.9,Smartphone,5.3,1,True,Always,27.0,68,3.14,Neutral
23,STU_2024023,17,Female,High School,Instagram,11.2,1.7,Smartphone,5.2,2,True,Sometimes,22.0,54,2.69,Neutral
31,STU_2024031,20,Male,Undergraduate,X (Twitter),8.3,1.8,Smartphone,5.6,1,True,Rarely,22.0,64,3.35,Neutral
80,STU_2024080,18,Female,Undergraduate,TikTok,8.5,1.8,Smartphone,5.5,1,True,Sometimes,24.0,67,2.79,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4443,STU_2028443,19,Male,Undergraduate,Instagram,9.5,1.9,Smartphone,5.1,1,True,Never,16.0,70,2.38,Neutral
4450,STU_2028450,21,Male,Undergraduate,YouTube,9.9,1.7,Smartphone,5.0,1,True,Sometimes,30.0,55,3.30,Neutral
4453,STU_2028453,18,Female,Undergraduate,Snapchat,9.1,2.4,Smartphone,5.4,3,False,Never,19.0,67,3.25,Neutral
4476,STU_2028476,17,Female,High School,TikTok,11.1,0.7,Smartphone,4.6,1,True,Rarely,32.0,53,2.56,Negative
4491,STU_2028491,18,Female,High School,YouTube,9.7,1.9,Smartphone,4.2,1,True,Sometimes,21.0,63,2.73,Neutral

In [318]:
print(two_conditions.shape[0]) # This will print the number of rows that meet both conditions

518

In [319]:
three_conditions = df[(df["Daily_Usage_Hours"] > 6) & (df["Sleep_Duration_Hours"] < 7)]
print(three_conditions)
display(three_conditions) # This will display the rows of the DataFrame where the daily usage hours are greater than 6 and the sleep duration hours are less than 7

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
0     STU_2024000   19             Female  Undergraduate         Snapchat
2     STU_2024002   17             Female    High School           TikTok
5     STU_2024005   16               Male    High School           TikTok
12    STU_2024012   19             Female  Undergraduate           TikTok
14    STU_2024014   19               Male  Undergraduate          YouTube
...           ...  ...                ...            ...              ...
4484  STU_2028484   21               Male  Undergraduate           TikTok
4486  STU_2028486   20             Female  Undergraduate           TikTok
4487  STU_2028487   17  Prefer not to say    High School        Instagram
4491  STU_2028491   18             Female    High School          YouTube
4497  STU_2028497   19               Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
2                  10.9                  1.7  Smartphone
5                   6.2                  1.6  Smartphone
12                  9.5                  0.9  Smartphone
14                  6.6                  2.3      Tablet
...                 ...                  ...         ...
4484                7.6                  1.0  Smartphone
4486                7.0                  1.8  Smartphone
4487                8.8                  2.5  Smartphone
4491                9.7                  1.9  Smartphone
4497                7.7                  1.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
2                      5.2                    1              True
5                      5.9                    1             False
12                     5.3                    1              True
14                     5.7                    3             False
...                    ...                  ...               ...
4484                   6.5                    1              True
4486                   5.4                    2              True
4487                   6.2                    1              True
4491                   4.2                    1              True
4497                   6.0                    2              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
2                     Frequently                    18.0                   70
5                         Rarely                    10.0                   66
12                        Always                    27.0                   68
14                     Sometimes                    17.0                   64
...                          ...                     ...                  ...
4484                   Sometimes                    17.0                   70
4486                  Frequently                    12.0                   75
4487                  Frequently                    21.0                   68
4491                   Sometimes                    21.0                   63
4497                  Frequently                    13.0                   73

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
2                         3.00        Neutral
5                         3.21     Beneficial
12                        3.14        Neutral
14                        2.98        Neutral
...                        ...            ...
4484                      3.49     Beneficial
4486                      3.23     Beneficial
4487                      3.50     Beneficial
4491                      2.73        Neutral
4497                      3.16     Beneficial

[1214 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
12,STU_2024012,19,Female,Undergraduate,TikTok,9.5,0.9,Smartphone,5.3,1,True,Always,27.0,68,3.14,Neutral
14,STU_2024014,19,Male,Undergraduate,YouTube,6.6,2.3,Tablet,5.7,3,False,Sometimes,17.0,64,2.98,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4484,STU_2028484,21,Male,Undergraduate,TikTok,7.6,1.0,Smartphone,6.5,1,True,Sometimes,17.0,70,3.49,Beneficial
4486,STU_2028486,20,Female,Undergraduate,TikTok,7.0,1.8,Smartphone,5.4,2,True,Frequently,12.0,75,3.23,Beneficial
4487,STU_2028487,17,Prefer not to say,High School,Instagram,8.8,2.5,Smartphone,6.2,1,True,Frequently,21.0,68,3.50,Beneficial
4491,STU_2028491,18,Female,High School,YouTube,9.7,1.9,Smartphone,4.2,1,True,Sometimes,21.0,63,2.73,Neutral
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial

In [320]:
four_conditions = df[(df["Daily_Usage_Hours"] > 5) & (df["Mental_Health_Index"] > 7)]
print(four_conditions)
display(four_conditions) # This will display the rows of the DataFrame where the daily usage hours are greater than 5 and the mental health score is less than 7

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
0     STU_2024000   19             Female  Undergraduate         Snapchat
2     STU_2024002   17             Female    High School           TikTok
3     STU_2024003   16             Female    High School          YouTube
5     STU_2024005   16               Male    High School           TikTok
6     STU_2024006   20               Male  Undergraduate           TikTok
...           ...  ...                ...            ...              ...
4487  STU_2028487   17  Prefer not to say    High School        Instagram
4491  STU_2028491   18             Female    High School          YouTube
4494  STU_2028494   16               Male    High School          YouTube
4495  STU_2028495   16               Male    High School          YouTube
4497  STU_2028497   19               Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
5                   6.2                  1.6  Smartphone
6                   5.6                  1.8  Smartphone
...                 ...                  ...         ...
4487                8.8                  2.5  Smartphone
4491                9.7                  1.9  Smartphone
4494                5.2                  1.6  Smartphone
4495                5.8                  1.2  Smartphone
4497                7.7                  1.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
2                      5.2                    1              True
3                      7.6                    4              True
5                      5.9                    1             False
6                      8.3                    3             False
...                    ...                  ...               ...
4487                   6.2                    1              True
4491                   4.2                    1              True
4494                   5.7                    3              True
4495                   7.8                    3              True
4497                   6.0                    2              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
5                         Rarely                    10.0                   66
6                      Sometimes                    10.0                   88
...                          ...                     ...                  ...
4487                  Frequently                    21.0                   68
4491                   Sometimes                    21.0                   63
4494                   Sometimes                    24.0                   77
4495                   Sometimes                    11.0                   79
4497                  Frequently                    13.0                   73

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
2                         3.00        Neutral
3                         3.42     Beneficial
5                         3.21     Beneficial
6                         3.72     Beneficial
...                        ...            ...
4487                      3.50     Beneficial
4491                      2.73        Neutral
4494                      3.31        Neutral
4495                      2.85     Beneficial
4497                      3.16     Beneficial

[1991 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
6,STU_2024006,20,Male,Undergraduate,TikTok,5.6,1.8,Smartphone,8.3,3,False,Sometimes,10.0,88,3.72,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4487,STU_2028487,17,Prefer not to say,High School,Instagram,8.8,2.5,Smartphone,6.2,1,True,Frequently,21.0,68,3.50,Beneficial
4491,STU_2028491,18,Female,High School,YouTube,9.7,1.9,Smartphone,4.2,1,True,Sometimes,21.0,63,2.73,Neutral
4494,STU_2028494,16,Male,High School,YouTube,5.2,1.6,Smartphone,5.7,3,True,Sometimes,24.0,77,3.31,Neutral
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial

In [321]:
five_conditions = df[(df["Daily_Usage_Hours"] > 6) & (df["Primary_Platform"] == "Instagram")]
print(five_conditions)
display(five_conditions) # This will display the rows of the DataFrame where the daily usage hours are greater than 6 and the primary platform is Instagram

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
23    STU_2024023   17             Female    High School        Instagram
43    STU_2024043   20               Male  Undergraduate        Instagram
44    STU_2024044   21             Female  Undergraduate        Instagram
94    STU_2024094   17             Female    High School        Instagram
113   STU_2024113   16             Female    High School        Instagram
...           ...  ...                ...            ...              ...
4416  STU_2028416   19             Female  Undergraduate        Instagram
4425  STU_2028425   19               Male  Undergraduate        Instagram
4443  STU_2028443   19               Male  Undergraduate        Instagram
4487  STU_2028487   17  Prefer not to say    High School        Instagram
4497  STU_2028497   19               Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
23                 11.2                  1.7  Smartphone
43                  8.3                  2.2  Smartphone
44                  7.6                  1.6  Smartphone
94                  8.8                  2.0  Smartphone
113                 6.6                  2.2  Smartphone
...                 ...                  ...         ...
4416                6.1                  1.8  Smartphone
4425               12.4                  1.2  Smartphone
4443                9.5                  1.9  Smartphone
4487                8.8                  2.5  Smartphone
4497                7.7                  1.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
23                     5.2                    2              True
43                     6.3                    1              True
44                     5.9                    1              True
94                     4.3                    1              True
113                    6.8                    2             False
...                    ...                  ...               ...
4416                   6.6                    2              True
4425                   5.8                    1              True
4443                   5.1                    1              True
4487                   6.2                    1              True
4497                   6.0                    2              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
23                     Sometimes               22.000000                   54
43                     Sometimes               13.000000                   76
44                        Rarely               25.000000                   70
94                        Rarely               19.000000                   68
113                   Frequently               13.000000                   85
...                          ...                     ...                  ...
4416                   Sometimes               17.000000                   75
4425                  Frequently               13.512124                   54
4443                       Never               16.000000                   70
4487                  Frequently               21.000000                   68
4497                  Frequently               13.000000                   73

      Academic_Performance_GPA Overall_Impact
23                    2.690000        Neutral
43                    3.210000     Beneficial
44                    3.429282        Neutral
94                    2.700000        Neutral
113                   3.480000     Beneficial
...                        ...            ...
4416                  3.010000     Beneficial
4425                  2.800000        Neutral
4443                  2.380000        Neutral
4487                  3.500000     Beneficial
4497                  3.160000     Beneficial

[431 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
23,STU_2024023,17,Female,High School,Instagram,11.2,1.7,Smartphone,5.2,2,True,Sometimes,22.000000,54,2.690000,Neutral
43,STU_2024043,20,Male,Undergraduate,Instagram,8.3,2.2,Smartphone,6.3,1,True,Sometimes,13.000000,76,3.210000,Beneficial
44,STU_2024044,21,Female,Undergraduate,Instagram,7.6,1.6,Smartphone,5.9,1,True,Rarely,25.000000,70,3.429282,Neutral
94,STU_2024094,17,Female,High School,Instagram,8.8,2.0,Smartphone,4.3,1,True,Rarely,19.000000,68,2.700000,Neutral
113,STU_2024113,16,Female,High School,Instagram,6.6,2.2,Smartphone,6.8,2,False,Frequently,13.000000,85,3.480000,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4416,STU_2028416,19,Female,Undergraduate,Instagram,6.1,1.8,Smartphone,6.6,2,True,Sometimes,17.000000,75,3.010000,Beneficial
4425,STU_2028425,19,Male,Undergraduate,Instagram,12.4,1.2,Smartphone,5.8,1,True,Frequently,13.512124,54,2.800000,Neutral
4443,STU_2028443,19,Male,Undergraduate,Instagram,9.5,1.9,Smartphone,5.1,1,True,Never,16.000000,70,2.380000,Neutral
4487,STU_2028487,17,Prefer not to say,High School,Instagram,8.8,2.5,Smartphone,6.2,1,True,Frequently,21.000000,68,3.500000,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.000000,73,3.160000,Beneficial

In [ ]:
six_conditions = df[(df["Daily_Usage_Hours"] > 5) & (df["Sleep_Duration_Hours"] < 7) & (df["Mental_Health_Index"] > 5) & (df["Primary_Platform"] == "Youtube")]
print(six_conditions)
display(six_conditions) # This will display the rows of the DataFrame where the daily usage hours are greater than 6 and the sleep duration hours are less than 7