In [1]:
import pandas as pd
import matplotlib.pyplot as plt

Loading the Dataset

In [2]:
df = pd.read_csv("social_media_impact.csv")

In [3]:
print(df)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat
1     STU_2024001   19  Female  Undergraduate        Instagram
2     STU_2024002   17  Female    High School           TikTok
3     STU_2024003   16  Female    High School          YouTube
4     STU_2024004   17    Male    High School         LinkedIn
...           ...  ...     ...            ...              ...
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone
1                   4.6                  1.3  Smartphone
2                  10.9                  1.7  Smartphone
3                   6.0                  2.3      Tablet
4                   3.3                  2.6  Smartphone
...                 ...                  ...         ...
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
0                      5.9                    2              True
1                      7.9                    3              True
2                      5.2                    1              True
3                      7.6                    4              True
4                      7.6                    4              True
...                    ...                  ...               ...
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
0                         Always                    20.0                   73
1                      Sometimes                    17.0                   90
2                     Frequently                    18.0                   70
3                      Sometimes                    15.0                   82
4                          Never                    16.0                   84
...                          ...                     ...                  ...
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
0                         2.73        Neutral
1                         3.21     Beneficial
2                         3.00        Neutral
3                         3.42     Beneficial
4                         3.41     Beneficial
...                        ...            ...
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

[4500 rows x 16 columns]

In [4]:
display(df.head())

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial

In [5]:
print(df.head())
display(df.head())

    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok
3  STU_2024003   16  Female    High School          YouTube
4  STU_2024004   17    Male    High School         LinkedIn

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2
3                6.0                  2.3      Tablet                   7.6
4                3.3                  2.6  Smartphone                   7.6

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently
3                    4              True                   Sometimes
4                    4              True                       Never

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00
3                    15.0                   82                      3.42
4                    16.0                   84                      3.41

  Overall_Impact
0        Neutral
1     Beneficial
2        Neutral
3     Beneficial
4     Beneficial

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial

In [6]:
print("First ten rows of data set: ") #this printing line describing what you will see in the terminal.
print(df.head(10))
display(df.head(10))

First ten rows of data set:
    Student_ID  Age  Gender Academic_Level Primary_Platform  \
0  STU_2024000   19  Female  Undergraduate         Snapchat
1  STU_2024001   19  Female  Undergraduate        Instagram
2  STU_2024002   17  Female    High School           TikTok
3  STU_2024003   16  Female    High School          YouTube
4  STU_2024004   17    Male    High School         LinkedIn
5  STU_2024005   16    Male    High School           TikTok
6  STU_2024006   20    Male  Undergraduate           TikTok
7  STU_2024007   19  Female  Undergraduate           TikTok
8  STU_2024008   18  Female  Undergraduate          YouTube
9  STU_2024009   18  Female  Undergraduate           Reddit

   Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  Sleep_Duration_Hours  \
0                7.5                  1.5  Smartphone                   5.9
1                4.6                  1.3  Smartphone                   7.9
2               10.9                  1.7  Smartphone                   5.2
3                6.0                  2.3      Tablet                   7.6
4                3.3                  2.6  Smartphone                   7.6
5                6.2                  1.6  Smartphone                   5.9
6                5.6                  1.8  Smartphone                   8.3
7                1.2                  2.4  Smartphone                   8.1
8                3.3                  1.8  Smartphone                   6.4
9                4.7                  1.7  Smartphone                   7.9

   Sleep_Quality_Score  Late_Night_Usage Social_Comparison_Frequency  \
0                    2              True                      Always
1                    3              True                   Sometimes
2                    1              True                  Frequently
3                    4              True                   Sometimes
4                    4              True                       Never
5                    1             False                      Rarely
6                    3             False                   Sometimes
7                    5             False                      Always
8                    2             False                  Frequently
9                    2             False                  Frequently

   Perceived_Stress_Score  Mental_Health_Index  Academic_Performance_GPA  \
0                    20.0                   73                      2.73
1                    17.0                   90                      3.21
2                    18.0                   70                      3.00
3                    15.0                   82                      3.42
4                    16.0                   84                      3.41
5                    10.0                   66                      3.21
6                    10.0                   88                      3.72
7                     6.0                   95                      3.37
8                    23.0                   88                      3.59
9                     6.0                   96                      3.66

  Overall_Impact
0        Neutral
1     Beneficial
2        Neutral
3     Beneficial
4     Beneficial
5     Beneficial
6     Beneficial
7     Beneficial
8     Beneficial
9     Beneficial

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
6,STU_2024006,20,Male,Undergraduate,TikTok,5.6,1.8,Smartphone,8.3,3,False,Sometimes,10.0,88,3.72,Beneficial
7,STU_2024007,19,Female,Undergraduate,TikTok,1.2,2.4,Smartphone,8.1,5,False,Always,6.0,95,3.37,Beneficial
8,STU_2024008,18,Female,Undergraduate,YouTube,3.3,1.8,Smartphone,6.4,2,False,Frequently,23.0,88,3.59,Beneficial
9,STU_2024009,18,Female,Undergraduate,Reddit,4.7,1.7,Smartphone,7.9,2,False,Frequently,6.0,96,3.66,Beneficial

In [7]:
print(df.tail())
display(df.tail())

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [8]:
print(df.tail(10))
display(df.tail(10))

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
4490  STU_2028490   19    Male  Undergraduate           TikTok
4491  STU_2028491   18  Female    High School          YouTube
4492  STU_2028492   22    Male   Postgraduate         Snapchat
4493  STU_2028493   18  Female  Undergraduate          YouTube
4494  STU_2028494   16    Male    High School          YouTube
4495  STU_2028495   16    Male    High School          YouTube
4496  STU_2028496   19  Female  Undergraduate         LinkedIn
4497  STU_2028497   19    Male  Undergraduate        Instagram
4498  STU_2028498   16    Male    High School         LinkedIn
4499  STU_2028499   24    Male  Undergraduate        Instagram

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
4490                4.0                  1.8  Smartphone
4491                9.7                  1.9  Smartphone
4492                3.6                  2.5  Smartphone
4493                4.5                  2.4  Smartphone
4494                5.2                  1.6  Smartphone
4495                5.8                  1.2  Smartphone
4496                3.8                  3.0  Smartphone
4497                7.7                  1.1  Smartphone
4498                4.6                  3.3   Laptop/PC
4499                1.8                  2.1  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
4490                   6.3                    3             False
4491                   4.2                    1              True
4492                   7.0                    4              True
4493                   8.2                    4              True
4494                   5.7                    3              True
4495                   7.8                    3              True
4496                   6.6                    3             False
4497                   6.0                    2              True
4498                   7.1                    3             False
4499                   6.8                    3              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
4490                   Sometimes                    13.0                   74
4491                   Sometimes                    21.0                   63
4492                  Frequently                    11.0                   92
4493                   Sometimes                     0.0                   85
4494                   Sometimes                    24.0                   77
4495                   Sometimes                    11.0                   79
4496                  Frequently                     9.0                   83
4497                  Frequently                    13.0                   73
4498                   Sometimes                    22.0                   87
4499                  Frequently                    10.0                   98

      Academic_Performance_GPA Overall_Impact
4490                      4.00     Beneficial
4491                      2.73        Neutral
4492                      3.42     Beneficial
4493                      3.75     Beneficial
4494                      3.31        Neutral
4495                      2.85     Beneficial
4496                      3.37     Beneficial
4497                      3.16     Beneficial
4498                      3.50     Beneficial
4499                      3.73     Beneficial

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
4490,STU_2028490,19,Male,Undergraduate,TikTok,4.0,1.8,Smartphone,6.3,3,False,Sometimes,13.0,74,4.00,Beneficial
4491,STU_2028491,18,Female,High School,YouTube,9.7,1.9,Smartphone,4.2,1,True,Sometimes,21.0,63,2.73,Neutral
4492,STU_2028492,22,Male,Postgraduate,Snapchat,3.6,2.5,Smartphone,7.0,4,True,Frequently,11.0,92,3.42,Beneficial
4493,STU_2028493,18,Female,Undergraduate,YouTube,4.5,2.4,Smartphone,8.2,4,True,Sometimes,0.0,85,3.75,Beneficial
4494,STU_2028494,16,Male,High School,YouTube,5.2,1.6,Smartphone,5.7,3,True,Sometimes,24.0,77,3.31,Neutral
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [9]:
print(df.shape)

(4500, 16)

In [10]:
print(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='str')

In [11]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   str
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   str
 3   Academic_Level               4500 non-null   str
 4   Primary_Platform             4500 non-null   str
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   str
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   str
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   str
dtypes: bool(1), float64(5), int64(3), str(7)
memory usage: 531.9 KB
None

In [12]:
print(df.isna().sum())

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Primary_Platform                0
Daily_Usage_Hours               0
Weekend_Extra_Hours             0
Device_Type                     0
Sleep_Duration_Hours            0
Sleep_Quality_Score             0
Late_Night_Usage                0
Social_Comparison_Frequency     0
Perceived_Stress_Score         46
Mental_Health_Index             0
Academic_Performance_GPA       85
Overall_Impact                  0
dtype: int64

In [13]:
average_stress = df["Perceived_Stress_Score"].mean()
print(average_stress)

13.512123933542883

In [14]:
average_gpa = df["Academic_Performance_GPA"].mean()
print(average_gpa)

3.4292819932049827

In [15]:
df["Perceived_Stress_Score"] = df["Perceived_Stress_Score"].fillna(average_stress)

In [16]:
df["Academic_Performance_GPA"] = df["Academic_Performance_GPA"].fillna(average_gpa)

In [17]:
print(df.isna().sum())

Student_ID                     0
Age                            0
Gender                         0
Academic_Level                 0
Primary_Platform               0
Daily_Usage_Hours              0
Weekend_Extra_Hours            0
Device_Type                    0
Sleep_Duration_Hours           0
Sleep_Quality_Score            0
Late_Night_Usage               0
Social_Comparison_Frequency    0
Perceived_Stress_Score         0
Mental_Health_Index            0
Academic_Performance_GPA       0
Overall_Impact                 0
dtype: int64

In [18]:
age_column = df["Age"]
print(age_column)

0       19
1       19
2       17
3       16
4       17
        ..
4495    16
4496    19
4497    19
4498    16
4499    24
Name: Age, Length: 4500, dtype: int64

In [19]:
print(age_column.describe())

count    4500.000000
mean       18.703333
std         1.981182
min        15.000000
25%        17.000000
50%        19.000000
75%        20.000000
max        26.000000
Name: Age, dtype: float64

In [20]:
primaty_platform_column = df["Primary_Platform"]
print(primaty_platform_column)

0        Snapchat
1       Instagram
2          TikTok
3         YouTube
4        LinkedIn
          ...
4495      YouTube
4496     LinkedIn
4497    Instagram
4498     LinkedIn
4499    Instagram
Name: Primary_Platform, Length: 4500, dtype: str

In [21]:
print(primaty_platform_column.value_counts())

Primary_Platform
Instagram      1453
TikTok         1226
YouTube         818
Snapchat        472
Reddit          229
X (Twitter)     206
LinkedIn         96
Name: count, dtype: int64

In [22]:
daily_usage_hours_column = df["Daily_Usage_Hours"]
print(daily_usage_hours_column)

0        7.5
1        4.6
2       10.9
3        6.0
4        3.3
        ...
4495     5.8
4496     3.8
4497     7.7
4498     4.6
4499     1.8
Name: Daily_Usage_Hours, Length: 4500, dtype: float64

In [23]:
print(df[daily_usage_hours_column > 8])

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
2     STU_2024002   17             Female    High School           TikTok
12    STU_2024012   19             Female  Undergraduate           TikTok
23    STU_2024023   17             Female    High School        Instagram
31    STU_2024031   20               Male  Undergraduate      X (Twitter)
43    STU_2024043   20               Male  Undergraduate        Instagram
...           ...  ...                ...            ...              ...
4453  STU_2028453   18             Female  Undergraduate         Snapchat
4475  STU_2028475   18             Female    High School           TikTok
4476  STU_2028476   17             Female    High School           TikTok
4487  STU_2028487   17  Prefer not to say    High School        Instagram
4491  STU_2028491   18             Female    High School          YouTube

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2                  10.9                  1.7  Smartphone
12                  9.5                  0.9  Smartphone
23                 11.2                  1.7  Smartphone
31                  8.3                  1.8  Smartphone
43                  8.3                  2.2  Smartphone
...                 ...                  ...         ...
4453                9.1                  2.4  Smartphone
4475                8.6                  1.5   Laptop/PC
4476               11.1                  0.7  Smartphone
4487                8.8                  2.5  Smartphone
4491                9.7                  1.9  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2                      5.2                    1              True
12                     5.3                    1              True
23                     5.2                    2              True
31                     5.6                    1              True
43                     6.3                    1              True
...                    ...                  ...               ...
4453                   5.4                    3             False
4475                   6.0                    1              True
4476                   4.6                    1              True
4487                   6.2                    1              True
4491                   4.2                    1              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2                     Frequently                    18.0                   70
12                        Always                    27.0                   68
23                     Sometimes                    22.0                   54
31                        Rarely                    22.0                   64
43                     Sometimes                    13.0                   76
...                          ...                     ...                  ...
4453                       Never                    19.0                   67
4475                   Sometimes                    18.0                   63
4476                      Rarely                    32.0                   53
4487                  Frequently                    21.0                   68
4491                   Sometimes                    21.0                   63

      Academic_Performance_GPA Overall_Impact
2                         3.00        Neutral
12                        3.14        Neutral
23                        2.69        Neutral
31                        3.35        Neutral
43                        3.21     Beneficial
...                        ...            ...
4453                      3.25        Neutral
4475                      3.24        Neutral
4476                      2.56       Negative
4487                      3.50     Beneficial
4491                      2.73        Neutral

[632 rows x 16 columns]

In [24]:
more_than_8h_online = df[daily_usage_hours_column > 8]
print(more_than_8h_online)

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
2     STU_2024002   17             Female    High School           TikTok
12    STU_2024012   19             Female  Undergraduate           TikTok
23    STU_2024023   17             Female    High School        Instagram
31    STU_2024031   20               Male  Undergraduate      X (Twitter)
43    STU_2024043   20               Male  Undergraduate        Instagram
...           ...  ...                ...            ...              ...
4453  STU_2028453   18             Female  Undergraduate         Snapchat
4475  STU_2028475   18             Female    High School           TikTok
4476  STU_2028476   17             Female    High School           TikTok
4487  STU_2028487   17  Prefer not to say    High School        Instagram
4491  STU_2028491   18             Female    High School          YouTube

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2                  10.9                  1.7  Smartphone
12                  9.5                  0.9  Smartphone
23                 11.2                  1.7  Smartphone
31                  8.3                  1.8  Smartphone
43                  8.3                  2.2  Smartphone
...                 ...                  ...         ...
4453                9.1                  2.4  Smartphone
4475                8.6                  1.5   Laptop/PC
4476               11.1                  0.7  Smartphone
4487                8.8                  2.5  Smartphone
4491                9.7                  1.9  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2                      5.2                    1              True
12                     5.3                    1              True
23                     5.2                    2              True
31                     5.6                    1              True
43                     6.3                    1              True
...                    ...                  ...               ...
4453                   5.4                    3             False
4475                   6.0                    1              True
4476                   4.6                    1              True
4487                   6.2                    1              True
4491                   4.2                    1              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2                     Frequently                    18.0                   70
12                        Always                    27.0                   68
23                     Sometimes                    22.0                   54
31                        Rarely                    22.0                   64
43                     Sometimes                    13.0                   76
...                          ...                     ...                  ...
4453                       Never                    19.0                   67
4475                   Sometimes                    18.0                   63
4476                      Rarely                    32.0                   53
4487                  Frequently                    21.0                   68
4491                   Sometimes                    21.0                   63

      Academic_Performance_GPA Overall_Impact
2                         3.00        Neutral
12                        3.14        Neutral
23                        2.69        Neutral
31                        3.35        Neutral
43                        3.21     Beneficial
...                        ...            ...
4453                      3.25        Neutral
4475                      3.24        Neutral
4476                      2.56       Negative
4487                      3.50     Beneficial
4491                      2.73        Neutral

[632 rows x 16 columns]

In [25]:
print(more_than_8h_online.shape)

(632, 16)

In [26]:
primary_platform_column = df["Primary_Platform"]
print(primary_platform_column)

0        Snapchat
1       Instagram
2          TikTok
3         YouTube
4        LinkedIn
          ...
4495      YouTube
4496     LinkedIn
4497    Instagram
4498     LinkedIn
4499    Instagram
Name: Primary_Platform, Length: 4500, dtype: str

In [27]:
tiktok_users = df[primary_platform_column == "TikTok"]
print(tiktok_users)

       Student_ID  Age             Gender Academic_Level Primary_Platform  \
2     STU_2024002   17             Female    High School           TikTok
5     STU_2024005   16               Male    High School           TikTok
6     STU_2024006   20               Male  Undergraduate           TikTok
7     STU_2024007   19             Female  Undergraduate           TikTok
10    STU_2024010   15             Female    High School           TikTok
...           ...  ...                ...            ...              ...
4483  STU_2028483   17             Female    High School           TikTok
4484  STU_2028484   21               Male  Undergraduate           TikTok
4486  STU_2028486   20             Female  Undergraduate           TikTok
4489  STU_2028489   21  Prefer not to say    High School           TikTok
4490  STU_2028490   19               Male  Undergraduate           TikTok

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2                  10.9                  1.7  Smartphone
5                   6.2                  1.6  Smartphone
6                   5.6                  1.8  Smartphone
7                   1.2                  2.4  Smartphone
10                  4.4                  1.9  Smartphone
...                 ...                  ...         ...
4483                5.3                  2.2  Smartphone
4484                7.6                  1.0  Smartphone
4486                7.0                  1.8  Smartphone
4489                2.8                  3.2  Smartphone
4490                4.0                  1.8  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2                      5.2                    1              True
5                      5.9                    1             False
6                      8.3                    3             False
7                      8.1                    5             False
10                     5.8                    2             False
...                    ...                  ...               ...
4483                   6.5                    3              True
4484                   6.5                    1              True
4486                   5.4                    2              True
4489                   7.2                    4              True
4490                   6.3                    3             False

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2                     Frequently                    18.0                   70
5                         Rarely                    10.0                   66
6                      Sometimes                    10.0                   88
7                         Always                     6.0                   95
10                    Frequently                    11.0                   83
...                          ...                     ...                  ...
4483                  Frequently                    13.0                   82
4484                   Sometimes                    17.0                   70
4486                  Frequently                    12.0                   75
4489                      Rarely                     6.0                   98
4490                   Sometimes                    13.0                   74

      Academic_Performance_GPA Overall_Impact
2                         3.00        Neutral
5                         3.21     Beneficial
6                         3.72     Beneficial
7                         3.37     Beneficial
10                        3.22     Beneficial
...                        ...            ...
4483                      3.02     Beneficial
4484                      3.49     Beneficial
4486                      3.23     Beneficial
4489                      3.86     Beneficial
4490                      4.00     Beneficial

[1226 rows x 16 columns]

In [28]:
print(tiktok_users.shape[0])

1226

In [29]:
two_conditions = df[
    (df["Daily_Usage_Hours"] > 8) & (df["Sleep_Duration_Hours"] < 6)
    ]
print(two_conditions)
display(two_conditions)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
2     STU_2024002   17  Female    High School           TikTok
12    STU_2024012   19  Female  Undergraduate           TikTok
23    STU_2024023   17  Female    High School        Instagram
31    STU_2024031   20    Male  Undergraduate      X (Twitter)
80    STU_2024080   18  Female  Undergraduate           TikTok
...           ...  ...     ...            ...              ...
4443  STU_2028443   19    Male  Undergraduate        Instagram
4450  STU_2028450   21    Male  Undergraduate          YouTube
4453  STU_2028453   18  Female  Undergraduate         Snapchat
4476  STU_2028476   17  Female    High School           TikTok
4491  STU_2028491   18  Female    High School          YouTube

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2                  10.9                  1.7  Smartphone
12                  9.5                  0.9  Smartphone
23                 11.2                  1.7  Smartphone
31                  8.3                  1.8  Smartphone
80                  8.5                  1.8  Smartphone
...                 ...                  ...         ...
4443                9.5                  1.9  Smartphone
4450                9.9                  1.7  Smartphone
4453                9.1                  2.4  Smartphone
4476               11.1                  0.7  Smartphone
4491                9.7                  1.9  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2                      5.2                    1              True
12                     5.3                    1              True
23                     5.2                    2              True
31                     5.6                    1              True
80                     5.5                    1              True
...                    ...                  ...               ...
4443                   5.1                    1              True
4450                   5.0                    1              True
4453                   5.4                    3             False
4476                   4.6                    1              True
4491                   4.2                    1              True

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2                     Frequently                    18.0                   70
12                        Always                    27.0                   68
23                     Sometimes                    22.0                   54
31                        Rarely                    22.0                   64
80                     Sometimes                    24.0                   67
...                          ...                     ...                  ...
4443                       Never                    16.0                   70
4450                   Sometimes                    30.0                   55
4453                       Never                    19.0                   67
4476                      Rarely                    32.0                   53
4491                   Sometimes                    21.0                   63

      Academic_Performance_GPA Overall_Impact
2                         3.00        Neutral
12                        3.14        Neutral
23                        2.69        Neutral
31                        3.35        Neutral
80                        2.79        Neutral
...                        ...            ...
4443                      2.38        Neutral
4450                      3.30        Neutral
4453                      3.25        Neutral
4476                      2.56       Negative
4491                      2.73        Neutral

[518 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
12,STU_2024012,19,Female,Undergraduate,TikTok,9.5,0.9,Smartphone,5.3,1,True,Always,27.0,68,3.14,Neutral
23,STU_2024023,17,Female,High School,Instagram,11.2,1.7,Smartphone,5.2,2,True,Sometimes,22.0,54,2.69,Neutral
31,STU_2024031,20,Male,Undergraduate,X (Twitter),8.3,1.8,Smartphone,5.6,1,True,Rarely,22.0,64,3.35,Neutral
80,STU_2024080,18,Female,Undergraduate,TikTok,8.5,1.8,Smartphone,5.5,1,True,Sometimes,24.0,67,2.79,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4443,STU_2028443,19,Male,Undergraduate,Instagram,9.5,1.9,Smartphone,5.1,1,True,Never,16.0,70,2.38,Neutral
4450,STU_2028450,21,Male,Undergraduate,YouTube,9.9,1.7,Smartphone,5.0,1,True,Sometimes,30.0,55,3.30,Neutral
4453,STU_2028453,18,Female,Undergraduate,Snapchat,9.1,2.4,Smartphone,5.4,3,False,Never,19.0,67,3.25,Neutral
4476,STU_2028476,17,Female,High School,TikTok,11.1,0.7,Smartphone,4.6,1,True,Rarely,32.0,53,2.56,Negative
4491,STU_2028491,18,Female,High School,YouTube,9.7,1.9,Smartphone,4.2,1,True,Sometimes,21.0,63,2.73,Neutral

In [30]:
print(two_conditions.shape[0])

518

In [31]:
sorted_daily_usage_hours = df.sort_values("Daily_Usage_Hours")

print(sorted_daily_usage_hours)
display(sorted_daily_usage_hours)

       Student_ID  Age      Gender Academic_Level Primary_Platform  \
2453  STU_2026453   18      Female  Undergraduate          YouTube
294   STU_2024294   19  Non-Binary  Undergraduate        Instagram
1473  STU_2025473   15      Female    High School          YouTube
3476  STU_2027476   17        Male    High School         Snapchat
2124  STU_2026124   19        Male  Undergraduate        Instagram
...           ...  ...         ...            ...              ...
4236  STU_2028236   16      Female    High School          YouTube
2236  STU_2026236   18      Female  Undergraduate           TikTok
595   STU_2024595   17        Male    High School        Instagram
2995  STU_2026995   17      Female    High School           TikTok
1742  STU_2025742   16        Male    High School           TikTok

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2453                0.9                  2.4  Smartphone
294                 1.0                  3.0  Smartphone
1473                1.0                  1.1  Smartphone
3476                1.1                  3.4  Smartphone
2124                1.1                  2.8  Smartphone
...                 ...                  ...         ...
4236               14.0                  1.6  Smartphone
2236               14.0                  3.4  Smartphone
595                14.0                  1.1  Smartphone
2995               14.0                  2.2  Smartphone
1742               14.0                  2.4  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2453                   7.6                    5             False
294                    9.2                    4              True
1473                   8.2                    4              True
3476                  10.1                    5              True
2124                   8.0                    3              True
...                    ...                  ...               ...
4236                   3.7                    1              True
2236                   4.0                    1              True
595                    4.3                    1             False
2995                   3.9                    1              True
1742                   4.5                    1             False

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2453                  Frequently                     9.0                   93
294                   Frequently                     0.0                   98
1473                      Rarely                     0.0                   98
3476                  Frequently                     5.0                   98
2124                  Frequently                     2.0                   96
...                          ...                     ...                  ...
4236                   Sometimes                    35.0                   32
2236                      Rarely                    30.0                   46
595                   Frequently                    32.0                   38
2995                       Never                    32.0                   35
1742                   Sometimes                    40.0                   45

      Academic_Performance_GPA Overall_Impact
2453                      3.59     Beneficial
294                       4.00     Beneficial
1473                      3.64     Beneficial
3476                      3.88     Beneficial
2124                      4.00     Beneficial
...                        ...            ...
4236                      2.50       Negative
2236                      2.43       Negative
595                       2.38       Negative
2995                      2.67       Negative
1742                      2.73       Negative

[4500 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
2453,STU_2026453,18,Female,Undergraduate,YouTube,0.9,2.4,Smartphone,7.6,5,False,Frequently,9.0,93,3.59,Beneficial
294,STU_2024294,19,Non-Binary,Undergraduate,Instagram,1.0,3.0,Smartphone,9.2,4,True,Frequently,0.0,98,4.00,Beneficial
1473,STU_2025473,15,Female,High School,YouTube,1.0,1.1,Smartphone,8.2,4,True,Rarely,0.0,98,3.64,Beneficial
3476,STU_2027476,17,Male,High School,Snapchat,1.1,3.4,Smartphone,10.1,5,True,Frequently,5.0,98,3.88,Beneficial
2124,STU_2026124,19,Male,Undergraduate,Instagram,1.1,2.8,Smartphone,8.0,3,True,Frequently,2.0,96,4.00,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4236,STU_2028236,16,Female,High School,YouTube,14.0,1.6,Smartphone,3.7,1,True,Sometimes,35.0,32,2.50,Negative
2236,STU_2026236,18,Female,Undergraduate,TikTok,14.0,3.4,Smartphone,4.0,1,True,Rarely,30.0,46,2.43,Negative
595,STU_2024595,17,Male,High School,Instagram,14.0,1.1,Smartphone,4.3,1,False,Frequently,32.0,38,2.38,Negative
2995,STU_2026995,17,Female,High School,TikTok,14.0,2.2,Smartphone,3.9,1,True,Never,32.0,35,2.67,Negative
1742,STU_2025742,16,Male,High School,TikTok,14.0,2.4,Smartphone,4.5,1,False,Sometimes,40.0,45,2.73,Negative

In [32]:
descending_daily_usage_hours = df.sort_values(
    "Daily_Usage_Hours",
    ascending=False
)

print(descending_daily_usage_hours)
display(descending_daily_usage_hours)

       Student_ID  Age      Gender Academic_Level Primary_Platform  \
2995  STU_2026995   17      Female    High School           TikTok
3392  STU_2027392   20      Female  Undergraduate           Reddit
3459  STU_2027459   21      Female  Undergraduate        Instagram
3449  STU_2027449   18      Female    High School           TikTok
2091  STU_2026091   17        Male    High School         Snapchat
...           ...  ...         ...            ...              ...
2124  STU_2026124   19        Male  Undergraduate        Instagram
3476  STU_2027476   17        Male    High School         Snapchat
294   STU_2024294   19  Non-Binary  Undergraduate        Instagram
1473  STU_2025473   15      Female    High School          YouTube
2453  STU_2026453   18      Female  Undergraduate          YouTube

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
2995               14.0                  2.2  Smartphone
3392               14.0                  1.9   Laptop/PC
3459               14.0                  1.6   Laptop/PC
3449               14.0                  1.8  Smartphone
2091               14.0                  1.0  Smartphone
...                 ...                  ...         ...
2124                1.1                  2.8  Smartphone
3476                1.1                  3.4  Smartphone
294                 1.0                  3.0  Smartphone
1473                1.0                  1.1  Smartphone
2453                0.9                  2.4  Smartphone

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
2995                   3.9                    1              True
3392                   3.0                    1              True
3459                   3.9                    1              True
3449                   4.2                    1              True
2091                   4.1                    1              True
...                    ...                  ...               ...
2124                   8.0                    3              True
3476                  10.1                    5              True
294                    9.2                    4              True
1473                   8.2                    4              True
2453                   7.6                    5             False

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
2995                       Never                    32.0                   35
3392                  Frequently                    40.0                   34
3459                   Sometimes                    35.0                   46
3449                      Rarely                    34.0                   41
2091                  Frequently                    31.0                   42
...                          ...                     ...                  ...
2124                  Frequently                     2.0                   96
3476                  Frequently                     5.0                   98
294                   Frequently                     0.0                   98
1473                      Rarely                     0.0                   98
2453                  Frequently                     9.0                   93

      Academic_Performance_GPA Overall_Impact
2995                      2.67       Negative
3392                      2.39       Negative
3459                      2.66       Negative
3449                      2.71       Negative
2091                      2.77       Negative
...                        ...            ...
2124                      4.00     Beneficial
3476                      3.88     Beneficial
294                       4.00     Beneficial
1473                      3.64     Beneficial
2453                      3.59     Beneficial

[4500 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
2995,STU_2026995,17,Female,High School,TikTok,14.0,2.2,Smartphone,3.9,1,True,Never,32.0,35,2.67,Negative
3392,STU_2027392,20,Female,Undergraduate,Reddit,14.0,1.9,Laptop/PC,3.0,1,True,Frequently,40.0,34,2.39,Negative
3459,STU_2027459,21,Female,Undergraduate,Instagram,14.0,1.6,Laptop/PC,3.9,1,True,Sometimes,35.0,46,2.66,Negative
3449,STU_2027449,18,Female,High School,TikTok,14.0,1.8,Smartphone,4.2,1,True,Rarely,34.0,41,2.71,Negative
2091,STU_2026091,17,Male,High School,Snapchat,14.0,1.0,Smartphone,4.1,1,True,Frequently,31.0,42,2.77,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,STU_2026124,19,Male,Undergraduate,Instagram,1.1,2.8,Smartphone,8.0,3,True,Frequently,2.0,96,4.00,Beneficial
3476,STU_2027476,17,Male,High School,Snapchat,1.1,3.4,Smartphone,10.1,5,True,Frequently,5.0,98,3.88,Beneficial
294,STU_2024294,19,Non-Binary,Undergraduate,Instagram,1.0,3.0,Smartphone,9.2,4,True,Frequently,0.0,98,4.00,Beneficial
1473,STU_2025473,15,Female,High School,YouTube,1.0,1.1,Smartphone,8.2,4,True,Rarely,0.0,98,3.64,Beneficial
2453,STU_2026453,18,Female,Undergraduate,YouTube,0.9,2.4,Smartphone,7.6,5,False,Frequently,9.0,93,3.59,Beneficial

In [33]:
sorted_platforms = df.sort_values("Primary_Platform")


print(sorted_platforms)
display(sorted_platforms)

       Student_ID  Age      Gender Academic_Level Primary_Platform  \
4499  STU_2028499   24        Male  Undergraduate        Instagram
3003  STU_2027003   19        Male  Undergraduate        Instagram
3004  STU_2027004   20  Non-Binary  Undergraduate        Instagram
1246  STU_2025246   22        Male   Postgraduate        Instagram
1243  STU_2025243   17      Female    High School        Instagram
...           ...  ...         ...            ...              ...
3807  STU_2027807   17        Male    High School          YouTube
2479  STU_2026479   17      Female    High School          YouTube
1654  STU_2025654   22        Male   Postgraduate          YouTube
2852  STU_2026852   21      Female    High School          YouTube
2411  STU_2026411   20      Female  Undergraduate          YouTube

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
4499                1.8                  2.1  Smartphone
3003                2.7                  1.2  Smartphone
3004                2.9                  2.0   Laptop/PC
1246                5.3                  2.0  Smartphone
1243                3.7                  2.5   Laptop/PC
...                 ...                  ...         ...
3807                3.8                  1.5  Smartphone
2479                8.1                  2.4   Laptop/PC
1654                5.7                  2.7  Smartphone
2852                5.8                  2.0  Smartphone
2411                5.0                  1.4   Laptop/PC

      Sleep_Duration_Hours  Sleep_Quality_Score  Late_Night_Usage  \
4499                   6.8                    3              True
3003                   8.5                    4             False
3004                   7.2                    3             False
1246                   5.8                    2              True
1243                   6.8                    2             False
...                    ...                  ...               ...
3807                   6.8                    3             False
2479                   6.3                    1              True
1654                   5.4                    1             False
2852                   5.8                    3              True
2411                   5.5                    2             False

     Social_Comparison_Frequency  Perceived_Stress_Score  Mental_Health_Index  \
4499                  Frequently               10.000000                   98
3003                       Never               15.000000                   95
3004                   Sometimes               23.000000                   81
1246                   Sometimes                9.000000                   80
1243                  Frequently                6.000000                   93
...                          ...                     ...                  ...
3807                  Frequently               11.000000                   78
2479                      Always               14.000000                   66
1654                  Frequently               15.000000                   86
2852                      Rarely               13.512124                   70
2411                      Always                8.000000                   89

      Academic_Performance_GPA Overall_Impact
4499                      3.73     Beneficial
3003                      3.93     Beneficial
3004                      3.36     Beneficial
1246                      3.14     Beneficial
1243                      3.87     Beneficial
...                        ...            ...
3807                      3.84     Beneficial
2479                      3.91     Beneficial
1654                      3.36     Beneficial
2852                      3.37     Beneficial
2411                      3.16     Beneficial

[4500 rows x 16 columns]

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.000000,98,3.73,Beneficial
3003,STU_2027003,19,Male,Undergraduate,Instagram,2.7,1.2,Smartphone,8.5,4,False,Never,15.000000,95,3.93,Beneficial
3004,STU_2027004,20,Non-Binary,Undergraduate,Instagram,2.9,2.0,Laptop/PC,7.2,3,False,Sometimes,23.000000,81,3.36,Beneficial
1246,STU_2025246,22,Male,Postgraduate,Instagram,5.3,2.0,Smartphone,5.8,2,True,Sometimes,9.000000,80,3.14,Beneficial
1243,STU_2025243,17,Female,High School,Instagram,3.7,2.5,Laptop/PC,6.8,2,False,Frequently,6.000000,93,3.87,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3807,STU_2027807,17,Male,High School,YouTube,3.8,1.5,Smartphone,6.8,3,False,Frequently,11.000000,78,3.84,Beneficial
2479,STU_2026479,17,Female,High School,YouTube,8.1,2.4,Laptop/PC,6.3,1,True,Always,14.000000,66,3.91,Beneficial
1654,STU_2025654,22,Male,Postgraduate,YouTube,5.7,2.7,Smartphone,5.4,1,False,Frequently,15.000000,86,3.36,Beneficial
2852,STU_2026852,21,Female,High School,YouTube,5.8,2.0,Smartphone,5.8,3,True,Rarely,13.512124,70,3.37,Beneficial
2411,STU_2026411,20,Female,Undergraduate,YouTube,5.0,1.4,Laptop/PC,5.5,2,False,Always,8.000000,89,3.16,Beneficial

In [34]:
sorted_platforms = df.sort_values(
    "Primary_Platform",
    ascending=False
)

#print(sorted_platforms)
display(sorted_platforms)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
3406,STU_2027406,16,Male,High School,YouTube,4.7,2.2,Smartphone,6.1,3,False,Always,22.0,82,3.40,Beneficial
890,STU_2024890,20,Male,High School,YouTube,2.4,1.6,Laptop/PC,6.6,2,True,Never,15.0,79,3.16,Beneficial
910,STU_2024910,21,Female,Undergraduate,YouTube,7.9,1.2,Smartphone,6.6,2,True,Never,18.0,76,3.31,Beneficial
2413,STU_2026413,17,Male,High School,YouTube,4.2,1.7,Smartphone,6.2,3,False,Always,5.0,81,3.50,Beneficial
2418,STU_2026418,17,Male,High School,YouTube,3.7,1.8,Smartphone,8.0,4,False,Frequently,5.0,88,3.36,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,STU_2026311,19,Female,Undergraduate,Instagram,3.9,1.5,Smartphone,7.2,3,True,Sometimes,6.0,86,3.84,Beneficial
2310,STU_2026310,16,Male,High School,Instagram,3.9,1.4,Smartphone,6.4,2,False,Frequently,17.0,82,3.41,Beneficial
2306,STU_2026306,19,Female,Undergraduate,Instagram,2.3,2.1,Smartphone,9.5,4,False,Always,8.0,88,3.74,Beneficial
2300,STU_2026300,17,Male,High School,Instagram,9.8,2.8,Smartphone,4.7,1,True,Sometimes,24.0,57,2.76,Neutral
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [35]:
display(df[["Age","Daily_Usage_Hours"]])

      Age  Daily_Usage_Hours
0      19                7.5
1      19                4.6
2      17               10.9
3      16                6.0
4      17                3.3
...   ...                ...
4495   16                5.8
4496   19                3.8
4497   19                7.7
4498   16                4.6
4499   24                1.8

[4500 rows x 2 columns]

In [43]:
group_by_age = df.groupby("Age")["Daily_Usage_Hours"].mean()
display(group_by_age)

Age
15    5.155488
16    5.493529
17    5.345810
18    5.365856
19    5.250998
20    5.310476
21    5.107865
22    5.173034
23    5.804706
24    4.446000
25    4.322727
26    4.920690
Name: Daily_Usage_Hours, dtype: float64

In [44]:
highest_usage_by_age = df.groupby("Age")["Daily_Usage_Hours"].max()
display(highest_usage_by_age)

Age
15    14.0
16    14.0
17    14.0
18    14.0
19    14.0
20    14.0
21    14.0
22    13.4
23    13.5
24     9.7
25    12.7
26     9.2
Name: Daily_Usage_Hours, dtype: float64